import React from 'react' 
import Image from 'next/image'; 
import hoodis from "../../../../public/hoodis.jpeg"; 
import { Metadata } from 'next/types';


export const metadata: Metadata = {
  title: "HOODIES",
  description: "Generated by create next app",
};
const hoodies = () => {
  return (
    <>
      <section className="text-gray-300 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-wrap -m-4">
            <div className="lg:w-1/4 md:w-1/2 p-4 w-full hover:scale-110 duration-500">
              <a className="block relative h-48 rounded overflow-hidden">
                <Image
                  alt="ecommerce"
                  width={400}
                  height={400}
                  objectFit="cover"
                  className="object-cover object-center w-full h-full block"
                  src={hoodis}
                />
              </a>
              <div className="mt-4">
                <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">
                  CATEGORY
                </h3>
                <h2 className="text-gray-900 title-font text-lg font-medium">
                  The Catalyzer
                </h2>
                <p className="mt-1">$16.00</p>
              </div>
            </div>
            <div className="lg:w-1/4 md:w-1/2 p-4 w-full hover:scale-110 duration-500">
              <a className="block relative h-48 rounded overflow-hidden">
                <Image
                  alt="ecommerce"
                  width={400}
                  height={400}
                  objectFit="cover"
                  className="object-cover object-center w-full h-full block"
                  src={hoodis}
                />
              </a>
              <div className="mt-4">
                <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">
                  CATEGORY
                </h3>
                <h2 className="text-gray-900 title-font text-lg font-medium">
                  Shooting Stars
                </h2>
                <p className="mt-1">$21.15</p>
              </div>
            </div>
            <div className="lg:w-1/4 md:w-1/2 p-4 w-full hover:scale-110 duration-500">
              <a className="block relative h-48 rounded overflow-hidden">
                <Image
                  alt="ecommerce"
                  width={400}
                  height={400}
                  objectFit="cover"
                  className="object-cover object-center w-full h-full block"
                  src={hoodis}
                />
              </a>
              <div className="mt-4">
                <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">
                  CATEGORY
                </h3>
                <h2 className="text-gray-900 title-font text-lg font-medium">
                  Neptune
                </h2>
                <p className="mt-1">$12.00</p>
              </div>
            </div>

            <div className="lg:w-1/4 md:w-1/2 p-4 w-full hover:scale-110 duration-500">
              <a className="block relative h-48 rounded overflow-hidden">
                <Image
                  alt="ecommerce"
                  width={400}
                  height={400}
                  objectFit="cover"
                  className="object-cover object-center w-full h-full block"
                  src={hoodis}
                />
              </a>
              <div className="mt-4">
                <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">
                  CATEGORY
                </h3>
                <h2 className="text-gray-900 title-font text-lg font-medium">
                  Neptune
                </h2>
                <p className="mt-1">$12.00</p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

export default hoodies
